import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Modal from "./Components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nodirbek | MyBlit.uz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-white" lang="en">
      <body className={`${inter.className} h-full bg-[url(/shine.pn)] ]`}>
        {children}
        <Modal />
      </body>
    </html>
  );
}
